trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pwd
    ls -la
    terraform init
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'
  workingDirectory: $(System.DefaultWorkingDirectory)/azure/environments/prod
  env:
    ARM_CLIENT_ID: $(AZ_CLIENT_ID)
    ARM_CLIENT_SECRET: $(AZ_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(AZ_SUBSCRIPRION_ID)
    ARM_TENANT_ID: $(AZ_TENANT_ID)

- script: |
    terraform apply -input=false tfplan
  displayName: 'Terraform Apply'
  workingDirectory: $(System.DefaultWorkingDirectory)/azure/environments/prod
  env:
    ARM_CLIENT_ID: $(AZ_CLIENT_ID)
    ARM_CLIENT_SECRET: $(AZ_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(AZ_SUBSCRIPRION_ID)
    ARM_TENANT_ID: $(AZ_TENANT_ID)
